### PR TITLE
Ansible 2.2 compat

### PR DESCRIPTION
**Pull request by toopy**
Avoids errors like this encountered with ansible 2.2:

``` bash
TASK [contrib.rabbitmq : Ensure the users is present] **************************
fatal: [services.lxc]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'user'\n\nThe error appears to have been in '/home/florent/work/**/ansible/roles/contrib.rabbitmq/tasks/rabbitmq.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure the users is present\n  ^ here\n"}
```

### CODE REVIEW

**Comment by homelessnessbo** [comment]
Made in last commits, now it works with ansible 2.2
